name: run main.py

on:
  workflow_dispatch:
      inputs:
        ticker:
          description: "Ticker da ação (ex: itsa4):"
          required: true
          type: string
        quote_day_ago:
          description: "Cotação de quantos dias atrás (ex: 3, 4):"
          required: true
          type: string
        ticker_diff:
          description: "Diferença entre os tickers: (ex: 0.10. Irá encontrar a diferença em reais entre o ticker digitado acima os outros tipos PN, ON, UNIT)"
          required: true
          type: number

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute main.py
        run: python main.py
        env:
          TICKER: ${{ github.event.inputs.ticker }}
          DAYS_AGO: ${{ github.event.inputs.quote_day_ago }}
          TICKER_DIFF: ${{ github.event.inputs.ticker_diff }}

      - name: Show dispatch inputs
        run: echo "Workflow dispatch inputs ${{ github.event.inputs.ticker }} ${{ github.event.inputs.quote_day_ago }} ${{github.event.inputs.ticker_diff}}"
        
      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results
          git diff-index --quiet HEAD || (git commit -a -m "[UPDATE_ACTION] Results from ticker" --allow-empty)
          git push
